### ISSUE TITLE
Can you please provide a block diagram and steps for this

### ISSUE THREAD

**Issue by bipindixit** [doyleranpo/TE-Mini#2]
Can you please provide a block diagram and steps for this
i am trying to make my project based on this

**Comment by doyleranpo** [comment]
Hi I hope this helps

![image](https://user-images.githubusercontent.com/31151818/85207291-619cc200-b345-11ea-8e55-ac28bca56f31.png)

I wasn't able to get the update database function working, and the calculation based on stops started working because of an issue with my hardware, but let me know if I can help you with anything. I still have the schematics of the PCB if you need that just hit me up

**Comment by bipindixit** [comment]
Thank you. It is really helpful
